@startuml visualization_architecture
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Visualizations\n A generic Dashboard

start

    note right
        Objective: Standardization, automation for rinse & repeat use.
    end note

    partition "Load Data" {

        :Prepare and Load Data as 
         Pandas DataFrame (df);

    }

    partition "HTML Layout" {


        :Define Layout sections;
            note right
                Provide in order of display
                Default is 1 dropdown with 2 charts
                i.e. ['dropdown', 'graph', 'graph]
            end note

        :Configure dropdown (text & selection);
            note right
                text (default is generic)
                select type (single or multiple)
                Options & start_value (data dependent)
            end note

        :Inject Figures into each HTML layout;
            note right
                This is done using update functions
            end note

        :Inject tables into each HTML layout;
            note right
                This is done using update functions?
            end note

    }

    partition "Prepare Charts" {
        
        :Plan & Prepare charts;

        :Single Selection;
            note right
                Each chart data has multiple dfs. 
                Multiple charts will have dfs redefined.
                No filtering recommended
            end note

        :Multiple Selection;
            note right
                Each chart data has multiple dfs.
                Multiple charts will have dfs redefined.
                No filtering recommended. 
                Utilize dictionary of dfs?
            end note

    }




stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml